import type { BankState, Money } from './types';
import { appendRow, balanceOf } from './ledger';
import { applySettleAccount } from './interest';

export interface TransferInput {
  fromAccountId: string;
  /** Own-account transfer target. Exactly one of toAccountId/toContactId. */
  toAccountId?: string;
  /** Contact transfer target — money leaves the mock world. */
  toContactId?: string;
  amountMinor: Money;
  /**
   * Generated by the UI once per submit. Idempotency key — a double tap
   * replays as the SAME transfer and becomes a successful no-op, separate
   * from transferGroupId which only groups legs for display.
   */
  clientTransferId: string;
  nowISO: string;
}

export type TransferError = 'invalid_amount' | 'insufficient_funds' | 'same_account' | 'unknown_target';

export type TransferOutcome =
  | { ok: true; state: BankState }
  | { ok: false; error: TransferError };

const RECENT_IDS_CAP = 50;

/**
 * The whole transfer as one pure state transition; the store applies it in a
 * single synchronous set(), which is what makes it atomic (docs/spec.md §4).
 */
export function applyTransfer(state: BankState, input: TransferInput): TransferOutcome {
  if (state.recentTransferIds.includes(input.clientTransferId)) {
    return { ok: true, state }; // double tap = one successful transfer, not an error
  }
  if (!Number.isSafeInteger(input.amountMinor) || input.amountMinor <= 0) {
    return { ok: false, error: 'invalid_amount' };
  }
  if (input.fromAccountId === input.toAccountId) {
    return { ok: false, error: 'same_account' };
  }

  const from = state.accounts.find((a) => a.id === input.fromAccountId);
  const toAccount = input.toAccountId
    ? state.accounts.find((a) => a.id === input.toAccountId)
    : undefined;
  const toContact = input.toContactId
    ? state.contacts.find((c) => c.id === input.toContactId)
    : undefined;
  if (!from || (!toAccount && !toContact)) return { ok: false, error: 'unknown_target' };

  // Settle pending interest first — otherwise the balance check would reject
  // a transfer that unmaterialised interest actually covers.
  let next = applySettleAccount(state, input.fromAccountId, input.nowISO);
  if (toAccount) next = applySettleAccount(next, toAccount.id, input.nowISO);

  if (input.amountMinor > balanceOf(next, input.fromAccountId)) {
    return { ok: false, error: 'insufficient_funds' };
  }

  if (toAccount) {
    const groupId = `grp_${next.nextSeq}`;
    next = appendRow(next, {
      accountId: from.id,
      amountMinor: -input.amountMinor,
      kind: 'transfer_own_out',
      counterparty: toAccount.name,
      category: 'transfer',
      transferGroupId: groupId,
      createdAt: input.nowISO,
    });
    next = appendRow(next, {
      accountId: toAccount.id,
      amountMinor: input.amountMinor,
      kind: 'transfer_own_in',
      counterparty: from.name,
      category: 'transfer',
      transferGroupId: groupId,
      createdAt: input.nowISO,
    });
  } else if (toContact) {
    next = appendRow(next, {
      accountId: from.id,
      amountMinor: -input.amountMinor,
      kind: 'transfer_contact',
      counterparty: toContact.name,
      category: 'transfer',
      createdAt: input.nowISO,
    });
    next = {
      ...next,
      contacts: next.contacts.map((c) =>
        c.id === toContact.id ? { ...c, lastTransferAt: input.nowISO } : c,
      ),
    };
  }

  return {
    ok: true,
    state: {
      ...next,
      recentTransferIds: [...next.recentTransferIds, input.clientTransferId].slice(-RECENT_IDS_CAP),
    },
  };
}
