import type {
  BankState,
  Currency,
  Money,
  TransactionFxSnapshot,
} from './types';
import { appendRow, balanceOf } from './ledger';
import { applySettleAccount } from './interest';
import { convertMoney, quoteCrossRate } from './currency';

interface TransferInputBase {
  fromAccountId: string;
  amountMinor: Money;
  /**
   * Generated by the UI once per submit. Idempotency key — a double tap
   * replays as the SAME transfer and becomes a successful no-op, separate
   * from transferGroupId which only groups legs for display.
   */
  clientTransferId: string;
  nowISO: string;
}

/** Exactly one target is required, both by TypeScript callers and at runtime. */
export type TransferInput = TransferInputBase &
  (
    | { toAccountId: string; toContactId?: never }
    | { toAccountId?: never; toContactId: string }
  );

type WithoutNow<T> = T extends unknown ? Omit<T, 'nowISO'> : never;
export type TransferRequest = WithoutNow<TransferInput>;

export type TransferError =
  | 'invalid_amount'
  | 'invalid_client_transfer_id'
  | 'insufficient_funds'
  | 'same_account'
  | 'unknown_target'
  | 'invalid_exchange_rate'
  | 'converted_amount_too_small'
  | 'balance_overflow';

export type TransferOutcome =
  | {
      ok: true;
      state: BankState;
      /** False means the clientTransferId was already committed: successful no-op. */
      applied: boolean;
      /** Exact credited minor units for a newly applied own-account transfer. */
      incomingAmountMinor?: Money;
    }
  | { ok: false; error: TransferError };

const RECENT_IDS_CAP = 50;
const CLIENT_TRANSFER_ID_PATTERN = /^ct_[A-Za-z0-9_.:-]{1,96}$/;

export function isClientTransferId(value: unknown): value is string {
  return typeof value === 'string' && CLIENT_TRANSFER_ID_PATTERN.test(value);
}

function buildFxSnapshot(
  state: BankState,
  fromCurrency: Currency,
  toCurrency: Currency,
  fromAmountMinor: Money,
  toAmountMinor: Money,
): Readonly<TransactionFxSnapshot> {
  const fromUsdRate = state.exchangeRates.rates[fromCurrency];
  const toUsdRate = state.exchangeRates.rates[toCurrency];
  return Object.freeze({
    fromCurrency,
    toCurrency,
    fromAmountMinor,
    toAmountMinor,
    rate: quoteCrossRate(fromCurrency, toCurrency, fromUsdRate, toUsdRate),
    fromUsdRate,
    toUsdRate,
    asOf: state.exchangeRates.asOf,
    fetchedAt: state.exchangeRates.fetchedAt,
    source: state.exchangeRates.source,
  });
}

/**
 * The whole transfer as one pure state transition; the store applies it in a
 * single synchronous set(), which is what makes it atomic (docs/spec.md §4).
 */
export function applyTransfer(state: BankState, input: TransferInput): TransferOutcome {
  if (!isClientTransferId(input.clientTransferId)) {
    return { ok: false, error: 'invalid_client_transfer_id' };
  }
  if (state.recentTransferIds.includes(input.clientTransferId)) {
    return { ok: true, state, applied: false }; // double tap = one successful transfer, not an error
  }
  if (!Number.isSafeInteger(input.amountMinor) || input.amountMinor <= 0) {
    return { ok: false, error: 'invalid_amount' };
  }
  const hasAccountTarget = typeof input.toAccountId === 'string';
  const hasContactTarget = typeof input.toContactId === 'string';
  if (hasAccountTarget === hasContactTarget) {
    return { ok: false, error: 'unknown_target' };
  }
  if (input.fromAccountId === input.toAccountId) {
    return { ok: false, error: 'same_account' };
  }

  const from = state.accounts.find((a) => a.id === input.fromAccountId);
  const toAccount = input.toAccountId
    ? state.accounts.find((a) => a.id === input.toAccountId)
    : undefined;
  const toContact = input.toContactId
    ? state.contacts.find((c) => c.id === input.toContactId)
    : undefined;
  if (!from || (!toAccount && !toContact)) return { ok: false, error: 'unknown_target' };

  let targetAmountMinor = input.amountMinor;
  let fxSnapshot: Readonly<TransactionFxSnapshot> | undefined;
  if (toAccount && from.currency !== toAccount.currency) {
    try {
      targetAmountMinor = convertMoney(
        input.amountMinor,
        from.currency,
        toAccount.currency,
        state.exchangeRates,
      );
      fxSnapshot = buildFxSnapshot(
        state,
        from.currency,
        toAccount.currency,
        input.amountMinor,
        targetAmountMinor,
      );
    } catch (error: unknown) {
      if (error instanceof TypeError || error instanceof RangeError) {
        return { ok: false, error: 'invalid_exchange_rate' };
      }
      throw error;
    }
    if (targetAmountMinor === 0) {
      return { ok: false, error: 'converted_amount_too_small' };
    }
  }

  // Settle pending interest first — otherwise the balance check would reject
  // a transfer that unmaterialised interest actually covers.
  let next: BankState;
  try {
    next = applySettleAccount(state, input.fromAccountId, input.nowISO);
    if (toAccount) next = applySettleAccount(next, toAccount.id, input.nowISO);
  } catch (error: unknown) {
    if (error instanceof RangeError) return { ok: false, error: 'balance_overflow' };
    throw error;
  }

  if (input.amountMinor > balanceOf(next, input.fromAccountId)) {
    return { ok: false, error: 'insufficient_funds' };
  }

  try {
    if (toAccount) {
      const groupId = `grp_${next.nextSeq}`;
      const fxMetadata = fxSnapshot === undefined ? {} : { fxSnapshot };
      next = appendRow(next, {
        accountId: from.id,
        amountMinor: -input.amountMinor,
        kind: 'transfer_own_out',
        counterparty: toAccount.name,
        category: 'transfer',
        transferGroupId: groupId,
        ...fxMetadata,
        createdAt: input.nowISO,
      });
      next = appendRow(next, {
        accountId: toAccount.id,
        amountMinor: targetAmountMinor,
        kind: 'transfer_own_in',
        counterparty: from.name,
        category: 'transfer',
        transferGroupId: groupId,
        ...fxMetadata,
        createdAt: input.nowISO,
      });
    } else if (toContact) {
      next = appendRow(next, {
        accountId: from.id,
        amountMinor: -input.amountMinor,
        kind: 'transfer_contact',
        counterparty: toContact.name,
        category: 'transfer',
        createdAt: input.nowISO,
      });
      next = {
        ...next,
        contacts: next.contacts.map((c) =>
          c.id === toContact.id ? { ...c, lastTransferAt: input.nowISO } : c,
        ),
      };
    }
  } catch (error: unknown) {
    if (error instanceof RangeError) return { ok: false, error: 'balance_overflow' };
    throw error;
  }

  return {
    ok: true,
    applied: true,
    ...(toAccount ? { incomingAmountMinor: targetAmountMinor } : {}),
    state: {
      ...next,
      recentTransferIds: [...next.recentTransferIds, input.clientTransferId].slice(-RECENT_IDS_CAP),
    },
  };
}
